### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by coksvictoria** [gicsaw/ARAE_torch#2]
Hi, 

Thank you for sharing your code.
However I am having following error message when running ARAE_train.py in google colab.

Can you please help?

Thanks

!python ARAE_train.py

reconstruction accuracy: 0.7939578352532058 0.0
real:  C[C@@H]1CN(C(=O)NC(c2ccccc2)c2ccccc2)C[C@@H](C)O1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
AE  :  CCC@HH](CC(C(=O)Ncc=2ccccc2)C2ccccc2)C[C@HH]1C)O1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
real:  Fc1ccccc1-c1nnc(C[NH+]2CCC[C@@H]2COc2ccccc2)o1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
AE  :  Cc1cccc(1Cc1ccc(CNNH2]2CCC[C@HH]2c(c2ccccc2)n1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ARAE:  <C[C@H]1CCC[C@@H](NC(=O)NCc2ccc(C(F)(F)F)cc2)C1>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
0 train loss: AE  0.325 cri -0.035 gen  0.029
Traceback (most recent call last):
  File "ARAE_train.py", line 319, in <module>
    main()
  File "ARAE_train.py", line 271, in main
    out_decoding = model.AE(batch_x, batch_l, noise)
  File "/content/drive/My Drive/ARAE_torch-master/model/ARAE.py", line 252, in AE
    Zn = Z+noise
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by gicsaw** [comment]
Thanks for your interest in the code.
This is a problem caused by not moving the variable to the device.
I modified and updated the code as follows.

270             noise = mean0
271             out_decoding = model.AE(batch_x, batch_l, noise)

in line 270: 
noise = mean0
-> 
noise = mean0.to(device)
